# for api: /admin/get-table-column

patient_table_column = {
    'columns': [
        {
            'prop': 'patientName',
            'label': 'Patient Name',
            'show': 'true',

            'sortConsultationId': 'false',
            'sortDepartment': 'false',
            'sortName': 'true',
            'sortPrescriptionId': 'false',
            'sortPharmacyWindow': 'false',
            'sortExaminationId': 'false',
            'sortRehabilitationId': 'false',
            'sortSurgeryId': 'false',
            'sortHospitalizationId': 'false',
            'sortChargeId': 'false',
            'sortDescribableItemId': 'false',
            'sortCost': 'false',
            'sortPosition': 'false',
            'sortPatientId': 'false',
            'sortDoctorId': 'false',
            'sortNurseId': 'false',
            'sortHelpingStaffId': 'false',
            'sortPharmacyPickWindow': 'false',
            'sortSurgerySite': 'false',
            'sortTime': 'false',
            'sortRoomId': 'false',
        },
        {
            'prop': 'patientId',
            'label': 'Patient ID',
            'show': 'true',

            'sortConsultationId': 'false',
            'sortDepartment': 'false',
            'sortName': 'false',
            'sortPrescriptionId': 'false',
            'sortPharmacyWindow': 'false',
            'sortExaminationId': 'false',
            'sortRehabilitationId': 'false',
            'sortSurgeryId': 'false',
            'sortHospitalizationId': 'false',
            'sortChargeId': 'false',
            'sortDescribableItemId': 'false',
            'sortCost': 'false',
            'sortPosition': 'false',
            'sortPatientId': 'true',
            'sortDoctorId': 'false',
            'sortNurseId': 'false',
            'sortHelpingStaffId': 'false',
            'sortPharmacyPickWindow': 'false',
            'sortSurgerySite': 'false',
            'sortTime': 'false',
            'sortRoomId': 'false',
        },
        {
            'prop': 'registerTime',
            'label': 'Register Time',
            'show': 'true',

            'sortConsultationId': 'false',
            'sortDepartment': 'false',
            'sortName': 'false',
            'sortPrescriptionId': 'false',
            'sortPharmacyWindow': 'false',
            'sortExaminationId': 'false',
            'sortRehabilitationId': 'false',
            'sortSurgeryId': 'false',
            'sortHospitalizationId': 'false',
            'sortChargeId': 'false',
            'sortDescribableItemId': 'false',
            'sortCost': 'false',
            'sortPosition': 'false',
            'sortPatientId': 'false',
            'sortDoctorId': 'false',
            'sortNurseId': 'false',
            'sortHelpingStaffId': 'false',
            'sortPharmacyPickWindow': 'false',
            'sortSurgerySite': 'false',
            'sortTime': 'true',
            'sortRoomId': 'false',
        }
    ],
    'detailInfo': {
        'canDelete': 'true',
        'canEdit': 'false',
        'canShowDetail': 'true',

        'isConsultation': 'false',
        'propNameOfConsultationId': 'consultationId',
        'isPrescription': 'false',
        'propNameOfPrescriptionId': 'prescriptionId',
        'isExamination': 'false',
        'propNameOfExaminationId': 'examinationId',
        'isRehabilitation': 'false',
        'propNameOfRehabilitationId': 'rehabilitationId',
        'isSurgery': 'false',
        'propNameOfSurgeryId': 'surgeryId',
        'isHospitalization': 'false',
        'propNameOfHospitalizationId': 'hospitalizationId',
        'isCharge': 'false',
        'propNameOfChargeId': 'chargeId',
        'isPatient': 'true',
        'propNameOfPatientId': 'patientId',
        'isDoctor': 'false',
        'propNameOfDoctorId': 'doctorId',
        'isNurse': 'false',
        'propNameOfNurseId': 'nurseId',
        'isHelpingStaff': 'false',
        'propNameOfHelpingStaffId': 'helpingStaffId',
        'isRoom': 'false',
        'propNameOfRoomId': 'roomId',
        'isPrescriptionMedicine': 'false',
        'propOfPrescriptionMedicineId': 'prescriptionId#medicineId',
        'isSurgeryRecord': 'false',
        'propOfSurgeryRecordId': 'surgeryId#recordId',
    },
    'keyColumnPropName': 'patientId',  # must be unique
}

doctor_table_column = {
    'columns': [
        {
            'prop': 'doctorName',
            'label': 'Doctor Name',
            'show': 'true',

            'sortConsultationId': 'false',
            'sortDepartment': 'false',
            'sortName': 'true',
            'sortPrescriptionId': 'false',
            'sortPharmacyWindow': 'false',
            'sortExaminationId': 'false',
            'sortRehabilitationId': 'false',
            'sortSurgeryId': 'false',
            'sortHospitalizationId': 'false',
            'sortChargeId': 'false',
            'sortDescribableItemId': 'false',
            'sortCost': 'false',
            'sortPosition': 'false',
            'sortPatientId': 'false',
            'sortDoctorId': 'false',
            'sortNurseId': 'false',
            'sortHelpingStaffId': 'false',
            'sortPharmacyPickWindow': 'false',
            'sortSurgerySite': 'false',
            'sortTime': 'false',
            'sortRoomId': 'false',
        },
        {
            'prop': 'doctorId',
            'label': 'Doctor ID',
            'show': 'true',

            'sortConsultationId': 'false',
            'sortDepartment': 'false',
            'sortName': 'false',
            'sortPrescriptionId': 'false',
            'sortPharmacyWindow': 'false',
            'sortExaminationId': 'false',
            'sortRehabilitationId': 'false',
            'sortSurgeryId': 'false',
            'sortHospitalizationId': 'false',
            'sortChargeId': 'false',
            'sortDescribableItemId': 'false',
            'sortCost': 'false',
            'sortPosition': 'false',
            'sortPatientId': 'false',
            'sortDoctorId': 'true',
            'sortNurseId': 'false',
            'sortHelpingStaffId': 'false',
            'sortPharmacyPickWindow': 'false',
            'sortSurgerySite': 'false',
            'sortTime': 'false',
            'sortRoomId': 'false',
        },
        {
            'prop': 'department',
            'label': 'Department',
            'show': 'true',

            'sortConsultationId': 'false',
            'sortDepartment': 'true',
            'sortName': 'false',
            'sortPrescriptionId': 'false',
            'sortPharmacyWindow': 'false',
            'sortExaminationId': 'false',
            'sortRehabilitationId': 'false',
            'sortSurgeryId': 'false',
            'sortHospitalizationId': 'false',
            'sortChargeId': 'false',
            'sortDescribableItemId': 'false',
            'sortCost': 'false',
            'sortPosition': 'false',
            'sortPatientId': 'false',
            'sortDoctorId': 'false',
            'sortNurseId': 'false',
            'sortHelpingStaffId': 'false',
            'sortPharmacyPickWindow': 'false',
            'sortSurgerySite': 'false',
            'sortTime': 'false',
            'sortRoomId': 'false',
        },
        {
            'prop': 'registerTime',
            'label': 'Register Time',
            'show': 'true',

            'sortConsultationId': 'false',
            'sortDepartment': 'false',
            'sortName': 'false',
            'sortPrescriptionId': 'false',
            'sortPharmacyWindow': 'false',
            'sortExaminationId': 'false',
            'sortRehabilitationId': 'false',
            'sortSurgeryId': 'false',
            'sortHospitalizationId': 'false',
            'sortChargeId': 'false',
            'sortDescribableItemId': 'false',
            'sortCost': 'false',
            'sortPosition': 'false',
            'sortPatientId': 'false',
            'sortDoctorId': 'false',
            'sortNurseId': 'false',
            'sortHelpingStaffId': 'false',
            'sortPharmacyPickWindow': 'false',
            'sortSurgerySite': 'false',
            'sortTime': 'true',
            'sortRoomId': 'false',
        }
    ],
    'detailInfo': {
        'canDelete': 'true',
        'canEdit': 'false',
        'canShowDetail': 'true',

        'isConsultation': 'false',
        'propNameOfConsultationId': 'consultationId',
        'isPrescription': 'false',
        'propNameOfPrescriptionId': 'prescriptionId',
        'isExamination': 'false',
        'propNameOfExaminationId': 'examinationId',
        'isRehabilitation': 'false',
        'propNameOfRehabilitationId': 'rehabilitationId',
        'isSurgery': 'false',
        'propNameOfSurgeryId': 'surgeryId',
        'isHospitalization': 'false',
        'propNameOfHospitalizationId': 'hospitalizationId',
        'isCharge': 'false',
        'propNameOfChargeId': 'chargeId',
        'isPatient': 'false',
        'propNameOfPatientId': 'patientId',
        'isDoctor': 'true',
        'propNameOfDoctorId': 'doctorId',
        'isNurse': 'false',
        'propNameOfNurseId': 'nurseId',
        'isHelpingStaff': 'false',
        'propNameOfHelpingStaffId': 'helpingStaffId',
        'isRoom': 'false',
        'propNameOfRoomId': 'roomId',
        'isPrescriptionMedicine': 'false',
        'propOfPrescriptionMedicineId': 'prescriptionId#medicineId',
        'isSurgeryRecord': 'false',
        'propOfSurgeryRecordId': 'surgeryId#recordId',
    },
    'keyColumnPropName': 'doctorId',  # must be unique
}

nurse_table_column = {
    'columns': [
        {
            'prop': 'nurseName',
            'label': 'Nurse Name',
            'show': 'true',

            'sortConsultationId': 'false',
            'sortDepartment': 'false',
            'sortName': 'true',
            'sortPrescriptionId': 'false',
            'sortPharmacyWindow': 'false',
            'sortExaminationId': 'false',
            'sortRehabilitationId': 'false',
            'sortSurgeryId': 'false',
            'sortHospitalizationId': 'false',
            'sortChargeId': 'false',
            'sortDescribableItemId': 'false',
            'sortCost': 'false',
            'sortPosition': 'false',
            'sortPatientId': 'false',
            'sortDoctorId': 'false',
            'sortNurseId': 'false',
            'sortHelpingStaffId': 'false',
            'sortPharmacyPickWindow': 'false',
            'sortSurgerySite': 'false',
            'sortTime': 'false',
            'sortRoomId': 'false',
        },
        {
            'prop': 'nurseId',
            'label': 'Nurse ID',
            'show': 'true',

            'sortConsultationId': 'false',
            'sortDepartment': 'false',
            'sortName': 'false',
            'sortPrescriptionId': 'false',
            'sortPharmacyWindow': 'false',
            'sortExaminationId': 'false',
            'sortRehabilitationId': 'false',
            'sortSurgeryId': 'false',
            'sortHospitalizationId': 'false',
            'sortChargeId': 'false',
            'sortDescribableItemId': 'false',
            'sortCost': 'false',
            'sortPosition': 'false',
            'sortPatientId': 'false',
            'sortDoctorId': 'false',
            'sortNurseId': 'true',
            'sortHelpingStaffId': 'false',
            'sortPharmacyPickWindow': 'false',
            'sortSurgerySite': 'false',
            'sortTime': 'false',
            'sortRoomId': 'false',
        },
        {
            'prop': 'roomId',
            'label': 'Room ID',
            'show': 'true',

            'sortConsultationId': 'false',
            'sortDepartment': 'false',
            'sortName': 'false',
            'sortPrescriptionId': 'false',
            'sortPharmacyWindow': 'false',
            'sortExaminationId': 'false',
            'sortRehabilitationId': 'false',
            'sortSurgeryId': 'false',
            'sortHospitalizationId': 'false',
            'sortChargeId': 'false',
            'sortDescribableItemId': 'false',
            'sortCost': 'false',
            'sortPosition': 'false',
            'sortPatientId': 'false',
            'sortDoctorId': 'false',
            'sortNurseId': 'false',
            'sortHelpingStaffId': 'false',
            'sortPharmacyPickWindow': 'false',
            'sortSurgerySite': 'false',
            'sortTime': 'false',
            'sortRoomId': 'true',
        },
        {
            'prop': 'registerTime',
            'label': 'Register Time',
            'show': 'true',

            'sortConsultationId': 'false',
            'sortDepartment': 'false',
            'sortName': 'false',
            'sortPrescriptionId': 'false',
            'sortPharmacyWindow': 'false',
            'sortExaminationId': 'false',
            'sortRehabilitationId': 'false',
            'sortSurgeryId': 'false',
            'sortHospitalizationId': 'false',
            'sortChargeId': 'false',
            'sortDescribableItemId': 'false',
            'sortCost': 'false',
            'sortPosition': 'false',
            'sortPatientId': 'false',
            'sortDoctorId': 'false',
            'sortNurseId': 'false',
            'sortHelpingStaffId': 'false',
            'sortPharmacyPickWindow': 'false',
            'sortSurgerySite': 'false',
            'sortTime': 'true',
            'sortRoomId': 'false',
        }
    ],
    'detailInfo': {
        'canDelete': 'true',
        'canEdit': 'false',
        'canShowDetail': 'true',

        'isConsultation': 'false',
        'propNameOfConsultationId': 'consultationId',
        'isPrescription': 'false',
        'propNameOfPrescriptionId': 'prescriptionId',
        'isExamination': 'false',
        'propNameOfExaminationId': 'examinationId',
        'isRehabilitation': 'false',
        'propNameOfRehabilitationId': 'rehabilitationId',
        'isSurgery': 'false',
        'propNameOfSurgeryId': 'surgeryId',
        'isHospitalization': 'false',
        'propNameOfHospitalizationId': 'hospitalizationId',
        'isCharge': 'false',
        'propNameOfChargeId': 'chargeId',
        'isPatient': 'false',
        'propNameOfPatientId': 'patientId',
        'isDoctor': 'false',
        'propNameOfDoctorId': 'doctorId',
        'isNurse': 'true',
        'propNameOfNurseId': 'nurseId',
        'isHelpingStaff': 'false',
        'propNameOfHelpingStaffId': 'helpingStaffId',
        'isRoom': 'false',
        'propNameOfRoomId': 'roomId',
        'isPrescriptionMedicine': 'false',
        'propOfPrescriptionMedicineId': 'prescriptionId#medicineId',
        'isSurgeryRecord': 'false',
        'propOfSurgeryRecordId': 'surgeryId#recordId',
    },
    'keyColumnPropName': 'nurseId',  # must be unique
}

helping_staff_table_column = {
    'columns': [
        {
            'prop': 'helpingStaffName',
            'label': 'Helping Staff Name',
            'show': 'true',

            'sortConsultationId': 'false',
            'sortDepartment': 'false',
            'sortName': 'true',
            'sortPrescriptionId': 'false',
            'sortPharmacyWindow': 'false',
            'sortExaminationId': 'false',
            'sortRehabilitationId': 'false',
            'sortSurgeryId': 'false',
            'sortHospitalizationId': 'false',
            'sortChargeId': 'false',
            'sortDescribableItemId': 'false',
            'sortCost': 'false',
            'sortPosition': 'false',
            'sortPatientId': 'false',
            'sortDoctorId': 'false',
            'sortNurseId': 'false',
            'sortHelpingStaffId': 'false',
            'sortPharmacyPickWindow': 'false',
            'sortSurgerySite': 'false',
            'sortTime': 'false',
            'sortRoomId': 'false',
        },
        {
            'prop': 'helpingStaffId',
            'label': 'Helping Staff ID',
            'show': 'true',

            'sortConsultationId': 'false',
            'sortDepartment': 'false',
            'sortName': 'false',
            'sortPrescriptionId': 'false',
            'sortPharmacyWindow': 'false',
            'sortExaminationId': 'false',
            'sortRehabilitationId': 'false',
            'sortSurgeryId': 'false',
            'sortHospitalizationId': 'false',
            'sortChargeId': 'false',
            'sortDescribableItemId': 'false',
            'sortCost': 'false',
            'sortPosition': 'false',
            'sortPatientId': 'false',
            'sortDoctorId': 'false',
            'sortNurseId': 'false',
            'sortHelpingStaffId': 'true',
            'sortPharmacyPickWindow': 'false',
            'sortSurgerySite': 'false',
            'sortTime': 'false',
            'sortRoomId': 'false',
        },
        {
            'prop': 'roomId',
            'label': 'Room ID',
            'show': 'true',

            'sortConsultationId': 'false',
            'sortDepartment': 'false',
            'sortName': 'false',
            'sortPrescriptionId': 'false',
            'sortPharmacyWindow': 'false',
            'sortExaminationId': 'false',
            'sortRehabilitationId': 'false',
            'sortSurgeryId': 'false',
            'sortHospitalizationId': 'false',
            'sortChargeId': 'false',
            'sortDescribableItemId': 'false',
            'sortCost': 'false',
            'sortPosition': 'false',
            'sortPatientId': 'false',
            'sortDoctorId': 'false',
            'sortNurseId': 'false',
            'sortHelpingStaffId': 'false',
            'sortPharmacyPickWindow': 'false',
            'sortSurgerySite': 'false',
            'sortTime': 'false',
            'sortRoomId': 'true',
        },
        {
            'prop': 'registerTime',
            'label': 'Register Time',
            'show': 'true',

            'sortConsultationId': 'false',
            'sortDepartment': 'false',
            'sortName': 'false',
            'sortPrescriptionId': 'false',
            'sortPharmacyWindow': 'false',
            'sortExaminationId': 'false',
            'sortRehabilitationId': 'false',
            'sortSurgeryId': 'false',
            'sortHospitalizationId': 'false',
            'sortChargeId': 'false',
            'sortDescribableItemId': 'false',
            'sortCost': 'false',
            'sortPosition': 'false',
            'sortPatientId': 'false',
            'sortDoctorId': 'false',
            'sortNurseId': 'false',
            'sortHelpingStaffId': 'false',
            'sortPharmacyPickWindow': 'false',
            'sortSurgerySite': 'false',
            'sortTime': 'true',
            'sortRoomId': 'false',
        }
    ],
    'detailInfo': {
        'canDelete': 'true',
        'canEdit': 'false',
        'canShowDetail': 'true',

        'isConsultation': 'false',
        'propNameOfConsultationId': 'consultationId',
        'isPrescription': 'false',
        'propNameOfPrescriptionId': 'prescriptionId',
        'isExamination': 'false',
        'propNameOfExaminationId': 'examinationId',
        'isRehabilitation': 'false',
        'propNameOfRehabilitationId': 'rehabilitationId',
        'isSurgery': 'false',
        'propNameOfSurgeryId': 'surgeryId',
        'isHospitalization': 'false',
        'propNameOfHospitalizationId': 'hospitalizationId',
        'isCharge': 'false',
        'propNameOfChargeId': 'chargeId',
        'isPatient': 'false',
        'propNameOfPatientId': 'patientId',
        'isDoctor': 'false',
        'propNameOfDoctorId': 'doctorId',
        'isNurse': 'false',
        'propNameOfNurseId': 'nurseId',
        'isHelpingStaff': 'true',
        'propNameOfHelpingStaffId': 'helpingStaffId',
        'isRoom': 'false',
        'propNameOfRoomId': 'roomId',
        'isPrescriptionMedicine': 'false',
        'propOfPrescriptionMedicineId': 'prescriptionId#medicineId',
        'isSurgeryRecord': 'false',
        'propOfSurgeryRecordId': 'surgeryId#recordId',
    },
    'keyColumnPropName': 'helpingStaffId',  # must be unique
}

medicine_table_column = {
    'columns': [
        {
            'prop': 'medicineName',
            'label': 'Medicine Name',
            'show': 'true',

            'sortConsultationId': 'false',
            'sortDepartment': 'false',
            'sortName': 'true',
            'sortPrescriptionId': 'false',
            'sortPharmacyWindow': 'false',
            'sortExaminationId': 'false',
            'sortRehabilitationId': 'false',
            'sortSurgeryId': 'false',
            'sortHospitalizationId': 'false',
            'sortChargeId': 'false',
            'sortDescribableItemId': 'false',
            'sortCost': 'false',
            'sortPosition': 'false',
            'sortPatientId': 'false',
            'sortDoctorId': 'false',
            'sortNurseId': 'false',
            'sortHelpingStaffId': 'false',
            'sortPharmacyPickWindow': 'false',
            'sortSurgerySite': 'false',
            'sortTime': 'false',
            'sortRoomId': 'false',
        },
        {
            'prop': 'medicineId',
            'label': 'Medicine ID',
            'show': 'true',

            'sortConsultationId': 'false',
            'sortDepartment': 'false',
            'sortName': 'false',
            'sortPrescriptionId': 'false',
            'sortPharmacyWindow': 'false',
            'sortExaminationId': 'false',
            'sortRehabilitationId': 'false',
            'sortSurgeryId': 'false',
            'sortHospitalizationId': 'false',
            'sortChargeId': 'false',
            'sortDescribableItemId': 'false',
            'sortCost': 'false',
            'sortPosition': 'false',
            'sortPatientId': 'false',
            'sortDoctorId': 'false',
            'sortNurseId': 'false',
            'sortHelpingStaffId': 'false',
            'sortPharmacyPickWindow': 'false',
            'sortSurgerySite': 'false',
            'sortTime': 'false',
            'sortRoomId': 'false',
        },
        {
            'prop': 'manufacturer',
            'label': 'Manufacturer',
            'show': 'true',

            'sortConsultationId': 'false',
            'sortDepartment': 'false',
            'sortName': 'false',
            'sortPrescriptionId': 'false',
            'sortPharmacyWindow': 'false',
            'sortExaminationId': 'false',
            'sortRehabilitationId': 'false',
            'sortSurgeryId': 'false',
            'sortHospitalizationId': 'false',
            'sortChargeId': 'false',
            'sortDescribableItemId': 'false',
            'sortCost': 'false',
            'sortPosition': 'false',
            'sortPatientId': 'false',
            'sortDoctorId': 'false',
            'sortNurseId': 'false',
            'sortHelpingStaffId': 'false',
            'sortPharmacyPickWindow': 'false',
            'sortSurgerySite': 'false',
            'sortTime': 'false',
            'sortRoomId': 'false',
        },
        {
            'prop': 'cost',
            'label': 'Cost',
            'show': 'true',

            'sortConsultationId': 'false',
            'sortDepartment': 'false',
            'sortName': 'false',
            'sortPrescriptionId': 'false',
            'sortPharmacyWindow': 'false',
            'sortExaminationId': 'false',
            'sortRehabilitationId': 'false',
            'sortSurgeryId': 'false',
            'sortHospitalizationId': 'false',
            'sortChargeId': 'false',
            'sortDescribableItemId': 'false',
            'sortCost': 'true',
            'sortPosition': 'false',
            'sortPatientId': 'false',
            'sortDoctorId': 'false',
            'sortNurseId': 'false',
            'sortHelpingStaffId': 'false',
            'sortPharmacyPickWindow': 'false',
            'sortSurgerySite': 'false',
            'sortTime': 'false',
            'sortRoomId': 'false',
        }
    ],
    'detailInfo': {
        'canDelete': 'true',
        'canEdit': 'false',
        'canShowDetail': 'false',

        'isConsultation': 'false',
        'propNameOfConsultationId': 'consultationId',
        'isPrescription': 'false',
        'propNameOfPrescriptionId': 'prescriptionId',
        'isExamination': 'false',
        'propNameOfExaminationId': 'examinationId',
        'isRehabilitation': 'false',
        'propNameOfRehabilitationId': 'rehabilitationId',
        'isSurgery': 'false',
        'propNameOfSurgeryId': 'surgeryId',
        'isHospitalization': 'false',
        'propNameOfHospitalizationId': 'hospitalizationId',
        'isCharge': 'false',
        'propNameOfChargeId': 'chargeId',
        'isPatient': 'false',
        'propNameOfPatientId': 'patientId',
        'isDoctor': 'false',
        'propNameOfDoctorId': 'doctorId',
        'isNurse': 'false',
        'propNameOfNurseId': 'nurseId',
        'isHelpingStaff': 'false',
        'propNameOfHelpingStaffId': 'helpingStaffId',
        'isRoom': 'false',
        'propNameOfRoomId': 'roomId',
        'isPrescriptionMedicine': 'false',
        'propOfPrescriptionMedicineId': 'prescriptionId#medicineId',
        'isSurgeryRecord': 'false',
        'propOfSurgeryRecordId': 'surgeryId#recordId',
    },
    'keyColumnPropName': 'medicineId',  # must be unique
}

examination_table_column = {
    'columns': [
        {
            'prop': 'examinationName',
            'label': 'Examination Name',
            'show': 'true',

            'sortConsultationId': 'false',
            'sortDepartment': 'false',
            'sortName': 'true',
            'sortPrescriptionId': 'false',
            'sortPharmacyWindow': 'false',
            'sortExaminationId': 'false',
            'sortRehabilitationId': 'false',
            'sortSurgeryId': 'false',
            'sortHospitalizationId': 'false',
            'sortChargeId': 'false',
            'sortDescribableItemId': 'false',
            'sortCost': 'false',
            'sortPosition': 'false',
            'sortPatientId': 'false',
            'sortDoctorId': 'false',
            'sortNurseId': 'false',
            'sortHelpingStaffId': 'false',
            'sortPharmacyPickWindow': 'false',
            'sortSurgerySite': 'false',
            'sortTime': 'false',
            'sortRoomId': 'false',
        },
        {
            'prop': 'examinationId',
            'label': 'Examination ID',
            'show': 'true',

            'sortConsultationId': 'false',
            'sortDepartment': 'false',
            'sortName': 'false',
            'sortPrescriptionId': 'false',
            'sortPharmacyWindow': 'false',
            'sortExaminationId': 'true',
            'sortRehabilitationId': 'false',
            'sortSurgeryId': 'false',
            'sortHospitalizationId': 'false',
            'sortChargeId': 'false',
            'sortDescribableItemId': 'false',
            'sortCost': 'false',
            'sortPosition': 'false',
            'sortPatientId': 'false',
            'sortDoctorId': 'false',
            'sortNurseId': 'false',
            'sortHelpingStaffId': 'false',
            'sortPharmacyPickWindow': 'false',
            'sortSurgerySite': 'false',
            'sortTime': 'false',
            'sortRoomId': 'false',
        },
        {
            'prop': 'cost',
            'label': 'Cost',
            'show': 'true',

            'sortConsultationId': 'false',
            'sortDepartment': 'false',
            'sortName': 'false',
            'sortPrescriptionId': 'false',
            'sortPharmacyWindow': 'false',
            'sortExaminationId': 'false',
            'sortRehabilitationId': 'false',
            'sortSurgeryId': 'false',
            'sortHospitalizationId': 'false',
            'sortChargeId': 'false',
            'sortDescribableItemId': 'false',
            'sortCost': 'true',
            'sortPosition': 'false',
            'sortPatientId': 'false',
            'sortDoctorId': 'false',
            'sortNurseId': 'false',
            'sortHelpingStaffId': 'false',
            'sortPharmacyPickWindow': 'false',
            'sortSurgerySite': 'false',
            'sortTime': 'false',
            'sortRoomId': 'false',
        },

    ],
    'detailInfo': {
        'canDelete': 'true',
        'canEdit': 'false',
        'canShowDetail': 'false',

        'isConsultation': 'false',
        'propNameOfConsultationId': 'consultationId',
        'isPrescription': 'false',
        'propNameOfPrescriptionId': 'prescriptionId',
        'isExamination': 'false',
        'propNameOfExaminationId': 'examinationId',
        'isRehabilitation': 'false',
        'propNameOfRehabilitationId': 'rehabilitationId',
        'isSurgery': 'false',
        'propNameOfSurgeryId': 'surgeryId',
        'isHospitalization': 'false',
        'propNameOfHospitalizationId': 'hospitalizationId',
        'isCharge': 'false',
        'propNameOfChargeId': 'chargeId',
        'isPatient': 'false',
        'propNameOfPatientId': 'patientId',
        'isDoctor': 'false',
        'propNameOfDoctorId': 'doctorId',
        'isNurse': 'false',
        'propNameOfNurseId': 'nurseId',
        'isHelpingStaff': 'false',
        'propNameOfHelpingStaffId': 'helpingStaffId',
        'isRoom': 'false',
        'propNameOfRoomId': 'roomId',
        'isPrescriptionMedicine': 'false',
        'propOfPrescriptionMedicineId': 'prescriptionId#medicineId',
        'isSurgeryRecord': 'false',
        'propOfSurgeryRecordId': 'surgeryId#recordId',
    },
    'keyColumnPropName': 'examinationId',  # must be unique
}

rehabilitation_table_column = {
    'columns': [
        {
            'prop': 'rehabilitationName',
            'label': 'Rehabilitation Name',
            'show': 'true',

            'sortConsultationId': 'false',
            'sortDepartment': 'false',
            'sortName': 'true',
            'sortPrescriptionId': 'false',
            'sortPharmacyWindow': 'false',
            'sortExaminationId': 'false',
            'sortRehabilitationId': 'false',
            'sortSurgeryId': 'false',
            'sortHospitalizationId': 'false',
            'sortChargeId': 'false',
            'sortDescribableItemId': 'false',
            'sortCost': 'false',
            'sortPosition': 'false',
            'sortPatientId': 'false',
            'sortDoctorId': 'false',
            'sortNurseId': 'false',
            'sortHelpingStaffId': 'false',
            'sortPharmacyPickWindow': 'false',
            'sortSurgerySite': 'false',
            'sortTime': 'false',
            'sortRoomId': 'false',
        },
        {
            'prop': 'rehabilitationId',
            'label': 'Rehabilitation ID',
            'show': 'true',

            'sortConsultationId': 'false',
            'sortDepartment': 'false',
            'sortName': 'false',
            'sortPrescriptionId': 'false',
            'sortPharmacyWindow': 'false',
            'sortExaminationId': 'false',
            'sortRehabilitationId': 'true',
            'sortSurgeryId': 'false',
            'sortHospitalizationId': 'false',
            'sortChargeId': 'false',
            'sortDescribableItemId': 'false',
            'sortCost': 'false',
            'sortPosition': 'false',
            'sortPatientId': 'false',
            'sortDoctorId': 'false',
            'sortNurseId': 'false',
            'sortHelpingStaffId': 'false',
            'sortPharmacyPickWindow': 'false',
            'sortSurgerySite': 'false',
            'sortTime': 'false',
            'sortRoomId': 'false',
        },
        {
            'prop': 'cost',
            'label': 'Cost',
            'show': 'true',

            'sortConsultationId': 'false',
            'sortDepartment': 'false',
            'sortName': 'false',
            'sortPrescriptionId': 'false',
            'sortPharmacyWindow': 'false',
            'sortExaminationId': 'false',
            'sortRehabilitationId': 'false',
            'sortSurgeryId': 'false',
            'sortHospitalizationId': 'false',
            'sortChargeId': 'false',
            'sortDescribableItemId': 'false',
            'sortCost': 'true',
            'sortPosition': 'false',
            'sortPatientId': 'false',
            'sortDoctorId': 'false',
            'sortNurseId': 'false',
            'sortHelpingStaffId': 'false',
            'sortPharmacyPickWindow': 'false',
            'sortSurgerySite': 'false',
            'sortTime': 'false',
            'sortRoomId': 'false',
        },

    ],
    'detailInfo': {
        'canDelete': 'true',
        'canEdit': 'false',
        'canShowDetail': 'false',

        'isConsultation': 'false',
        'propNameOfConsultationId': 'consultationId',
        'isPrescription': 'false',
        'propNameOfPrescriptionId': 'prescriptionId',
        'isExamination': 'false',
        'propNameOfExaminationId': 'examinationId',
        'isRehabilitation': 'false',
        'propNameOfRehabilitationId': 'rehabilitationId',
        'isSurgery': 'false',
        'propNameOfSurgeryId': 'surgeryId',
        'isHospitalization': 'false',
        'propNameOfHospitalizationId': 'hospitalizationId',
        'isCharge': 'false',
        'propNameOfChargeId': 'chargeId',
        'isPatient': 'false',
        'propNameOfPatientId': 'patientId',
        'isDoctor': 'false',
        'propNameOfDoctorId': 'doctorId',
        'isNurse': 'false',
        'propNameOfNurseId': 'nurseId',
        'isHelpingStaff': 'false',
        'propNameOfHelpingStaffId': 'helpingStaffId',
        'isRoom': 'false',
        'propNameOfRoomId': 'roomId',
        'isPrescriptionMedicine': 'false',
        'propOfPrescriptionMedicineId': 'prescriptionId#medicineId',
        'isSurgeryRecord': 'false',
        'propOfSurgeryRecordId': 'surgeryId#recordId',
    },
    'keyColumnPropName': 'rehabilitationId',  # must be unique
}

surgery_table_column = {
    'columns': [
        {
            'prop': 'surgeryName',
            'label': 'Surgery Name',
            'show': 'true',

            'sortConsultationId': 'false',
            'sortDepartment': 'false',
            'sortName': 'true',
            'sortPrescriptionId': 'false',
            'sortPharmacyWindow': 'false',
            'sortExaminationId': 'false',
            'sortRehabilitationId': 'false',
            'sortSurgeryId': 'false',
            'sortHospitalizationId': 'false',
            'sortChargeId': 'false',
            'sortDescribableItemId': 'false',
            'sortCost': 'false',
            'sortPosition': 'false',
            'sortPatientId': 'false',
            'sortDoctorId': 'false',
            'sortNurseId': 'false',
            'sortHelpingStaffId': 'false',
            'sortPharmacyPickWindow': 'false',
            'sortSurgerySite': 'false',
            'sortTime': 'false',
            'sortRoomId': 'false',
        },
        {
            'prop': 'surgeryId',
            'label': 'Surgery ID',
            'show': 'true',

            'sortConsultationId': 'false',
            'sortDepartment': 'false',
            'sortName': 'false',
            'sortPrescriptionId': 'false',
            'sortPharmacyWindow': 'false',
            'sortExaminationId': 'false',
            'sortRehabilitationId': 'false',
            'sortSurgeryId': 'true',
            'sortHospitalizationId': 'false',
            'sortChargeId': 'false',
            'sortDescribableItemId': 'false',
            'sortCost': 'false',
            'sortPosition': 'false',
            'sortPatientId': 'false',
            'sortDoctorId': 'false',
            'sortNurseId': 'false',
            'sortHelpingStaffId': 'false',
            'sortPharmacyPickWindow': 'false',
            'sortSurgerySite': 'false',
            'sortTime': 'false',
            'sortRoomId': 'false',
        },
        {
            'prop': 'cost',
            'label': 'Cost',
            'show': 'true',

            'sortConsultationId': 'false',
            'sortDepartment': 'false',
            'sortName': 'false',
            'sortPrescriptionId': 'false',
            'sortPharmacyWindow': 'false',
            'sortExaminationId': 'false',
            'sortRehabilitationId': 'false',
            'sortSurgeryId': 'false',
            'sortHospitalizationId': 'false',
            'sortChargeId': 'false',
            'sortDescribableItemId': 'false',
            'sortCost': 'true',
            'sortPosition': 'false',
            'sortPatientId': 'false',
            'sortDoctorId': 'false',
            'sortNurseId': 'false',
            'sortHelpingStaffId': 'false',
            'sortPharmacyPickWindow': 'false',
            'sortSurgerySite': 'false',
            'sortTime': 'false',
            'sortRoomId': 'false',
        },

    ],
    'detailInfo': {
        'canDelete': 'true',
        'canEdit': 'false',
        'canShowDetail': 'false',

        'isConsultation': 'false',
        'propNameOfConsultationId': 'consultationId',
        'isPrescription': 'false',
        'propNameOfPrescriptionId': 'prescriptionId',
        'isExamination': 'false',
        'propNameOfExaminationId': 'examinationId',
        'isRehabilitation': 'false',
        'propNameOfRehabilitationId': 'rehabilitationId',
        'isSurgery': 'false',
        'propNameOfSurgeryId': 'surgeryId',
        'isHospitalization': 'false',
        'propNameOfHospitalizationId': 'hospitalizationId',
        'isCharge': 'false',
        'propNameOfChargeId': 'chargeId',
        'isPatient': 'false',
        'propNameOfPatientId': 'patientId',
        'isDoctor': 'false',
        'propNameOfDoctorId': 'doctorId',
        'isNurse': 'false',
        'propNameOfNurseId': 'nurseId',
        'isHelpingStaff': 'false',
        'propNameOfHelpingStaffId': 'helpingStaffId',
        'isRoom': 'false',
        'propNameOfRoomId': 'roomId',
        'isPrescriptionMedicine': 'false',
        'propOfPrescriptionMedicineId': 'prescriptionId#medicineId',
        'isSurgeryRecord': 'false',
        'propOfSurgeryRecordId': 'surgeryId#recordId',
    },
    'keyColumnPropName': 'surgeryId',  # must be unique
}

department_table_column = {
    'columns': [
        {
            'prop': 'departmentName',
            'label': 'Department Name',
            'show': 'true',

            'sortConsultationId': 'false',
            'sortDepartment': 'false',
            'sortName': 'true',
            'sortPrescriptionId': 'false',
            'sortPharmacyWindow': 'false',
            'sortExaminationId': 'false',
            'sortRehabilitationId': 'false',
            'sortSurgeryId': 'false',
            'sortHospitalizationId': 'false',
            'sortChargeId': 'false',
            'sortDescribableItemId': 'false',
            'sortCost': 'false',
            'sortPosition': 'false',
            'sortPatientId': 'false',
            'sortDoctorId': 'false',
            'sortNurseId': 'false',
            'sortHelpingStaffId': 'false',
            'sortPharmacyPickWindow': 'false',
            'sortSurgerySite': 'false',
            'sortTime': 'false',
            'sortRoomId': 'false',
        },
    ],
    'detailInfo': {
        'canDelete': 'true',
        'canEdit': 'false',
        'canShowDetail': 'false',

        'isConsultation': 'false',
        'propNameOfConsultationId': 'consultationId',
        'isPrescription': 'false',
        'propNameOfPrescriptionId': 'prescriptionId',
        'isExamination': 'false',
        'propNameOfExaminationId': 'examinationId',
        'isRehabilitation': 'false',
        'propNameOfRehabilitationId': 'rehabilitationId',
        'isSurgery': 'false',
        'propNameOfSurgeryId': 'surgeryId',
        'isHospitalization': 'false',
        'propNameOfHospitalizationId': 'hospitalizationId',
        'isCharge': 'false',
        'propNameOfChargeId': 'chargeId',
        'isPatient': 'false',
        'propNameOfPatientId': 'patientId',
        'isDoctor': 'false',
        'propNameOfDoctorId': 'doctorId',
        'isNurse': 'false',
        'propNameOfNurseId': 'nurseId',
        'isHelpingStaff': 'false',
        'propNameOfHelpingStaffId': 'helpingStaffId',
        'isRoom': 'false',
        'propNameOfRoomId': 'roomId',
        'isPrescriptionMedicine': 'false',
        'propOfPrescriptionMedicineId': 'prescriptionId#medicineId',
        'isSurgeryRecord': 'false',
        'propOfSurgeryRecordId': 'surgeryId#recordId',
    },
    'keyColumnPropName': 'departmentName',  # must be unique
}

room_table_column = {
    'columns': [
        {
            'prop': 'roomId',
            'label': 'Room ID',
            'show': 'true',

            'sortConsultationId': 'false',
            'sortDepartment': 'false',
            'sortName': 'true',
            'sortPrescriptionId': 'false',
            'sortPharmacyWindow': 'false',
            'sortExaminationId': 'false',
            'sortRehabilitationId': 'false',
            'sortSurgeryId': 'false',
            'sortHospitalizationId': 'false',
            'sortChargeId': 'false',
            'sortDescribableItemId': 'false',
            'sortCost': 'false',
            'sortPosition': 'false',
            'sortPatientId': 'false',
            'sortDoctorId': 'false',
            'sortNurseId': 'false',
            'sortHelpingStaffId': 'false',
            'sortPharmacyPickWindow': 'false',
            'sortSurgerySite': 'false',
            'sortTime': 'false',
            'sortRoomId': 'false',
        },
        {
            'prop': 'roomType',
            'label': 'Room Type',
            'show': 'true',

            'sortConsultationId': 'false',
            'sortDepartment': 'false',
            'sortName': 'true',
            'sortPrescriptionId': 'false',
            'sortPharmacyWindow': 'false',
            'sortExaminationId': 'false',
            'sortRehabilitationId': 'false',
            'sortSurgeryId': 'false',
            'sortHospitalizationId': 'false',
            'sortChargeId': 'false',
            'sortDescribableItemId': 'false',
            'sortCost': 'false',
            'sortPosition': 'false',
            'sortPatientId': 'false',
            'sortDoctorId': 'false',
            'sortNurseId': 'false',
            'sortHelpingStaffId': 'false',
            'sortPharmacyPickWindow': 'false',
            'sortSurgerySite': 'false',
            'sortTime': 'false',
            'sortRoomId': 'false',
        },
        {
            'prop': 'bedNumber',
            'label': 'Number of Beds',
            'show': 'true',

            'sortConsultationId': 'false',
            'sortDepartment': 'false',
            'sortName': 'true',
            'sortPrescriptionId': 'false',
            'sortPharmacyWindow': 'false',
            'sortExaminationId': 'false',
            'sortRehabilitationId': 'false',
            'sortSurgeryId': 'false',
            'sortHospitalizationId': 'false',
            'sortChargeId': 'false',
            'sortDescribableItemId': 'false',
            'sortCost': 'false',
            'sortPosition': 'false',
            'sortPatientId': 'false',
            'sortDoctorId': 'false',
            'sortNurseId': 'false',
            'sortHelpingStaffId': 'false',
            'sortPharmacyPickWindow': 'false',
            'sortSurgerySite': 'false',
            'sortTime': 'false',
            'sortRoomId': 'false',
        },
        {
            'prop': 'additionalFacility',
            'label': 'Additional Facility',
            'show': 'true',

            'sortConsultationId': 'false',
            'sortDepartment': 'false',
            'sortName': 'true',
            'sortPrescriptionId': 'false',
            'sortPharmacyWindow': 'false',
            'sortExaminationId': 'false',
            'sortRehabilitationId': 'false',
            'sortSurgeryId': 'false',
            'sortHospitalizationId': 'false',
            'sortChargeId': 'false',
            'sortDescribableItemId': 'false',
            'sortCost': 'false',
            'sortPosition': 'false',
            'sortPatientId': 'false',
            'sortDoctorId': 'false',
            'sortNurseId': 'false',
            'sortHelpingStaffId': 'false',
            'sortPharmacyPickWindow': 'false',
            'sortSurgerySite': 'false',
            'sortTime': 'false',
            'sortRoomId': 'false',
        },
    ],
    'detailInfo': {
        'canDelete': 'true',
        'canEdit': 'false',
        'canShowDetail': 'true',

        'isConsultation': 'false',
        'propNameOfConsultationId': 'consultationId',
        'isPrescription': 'false',
        'propNameOfPrescriptionId': 'prescriptionId',
        'isExamination': 'false',
        'propNameOfExaminationId': 'examinationId',
        'isRehabilitation': 'false',
        'propNameOfRehabilitationId': 'rehabilitationId',
        'isSurgery': 'false',
        'propNameOfSurgeryId': 'surgeryId',
        'isHospitalization': 'false',
        'propNameOfHospitalizationId': 'hospitalizationId',
        'isCharge': 'false',
        'propNameOfChargeId': 'chargeId',
        'isPatient': 'false',
        'propNameOfPatientId': 'patientId',
        'isDoctor': 'false',
        'propNameOfDoctorId': 'doctorId',
        'isNurse': 'false',
        'propNameOfNurseId': 'nurseId',
        'isHelpingStaff': 'false',
        'propNameOfHelpingStaffId': 'helpingStaffId',
        'isRoom': 'true',
        'propNameOfRoomId': 'roomId',
        'isPrescriptionMedicine': 'false',
        'propOfPrescriptionMedicineId': 'prescriptionId#medicineId',
        'isSurgeryRecord': 'false',
        'propOfSurgeryRecordId': 'surgeryId#recordId',
    },
    'keyColumnPropName': 'roomId',  # must be unique
}